# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd1f8f269cd68e83d6c32df12d4aa1e89380b494089d6da4c2484cb74d39906c9a9f4dd2b75b69eb290280c412876167683438d09ab1d2d945eabfc1889b8d3b

test:
  secret_key_base: 7c5f8bf45d22a6ab93cbf2458d28365c4318980f4f237b4d666724de9c9a1302c0bc4a60452507f7e0104086ca0c5748ea9e9056655f5ada372c008e473a2f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
